'use client';

import { useMemo, useState } from 'react';
import Image from 'next/image';
import styles from './media-monitoring.module.css';

type Tab = 'Ringkasan' | 'Berita & Postingan' | 'Media & Akun' | 'Pencarian' | 'Analitik' | 'Peta & Relasi' | 'Tren';
type ContentRecord = {
  id: string; title: string; publisher: string; type: string; platform: string; topic: string; sentiment: string;
  reach: string; engagement: string; date: string; location: string; language: string; excerpt: string; author?: string; url?: string; video?: boolean;
};

const records: ContentRecord[] = [
  {
    id: 'MED-001', title: 'Pemkab Badung siapkan moda trem penghubung Kuta hingga Canggu', publisher: 'Portal Kabupaten Badung', author: 'I Made Surya Wijaya',
    type: 'Media Konvensional', platform: 'Media Online', topic: 'Kemacetan & Transportasi', sentiment: 'Neutral', reach: '24.8K',
    engagement: '1.2K', date: '02 Sep 2026', location: 'Kuta–Kuta Utara', language: 'Bahasa Indonesia',
    excerpt: 'Pemkab Badung dan PT KAI menyiapkan moda trem Bandara–Legian–Seminyak–Canggu sebagai solusi mobilitas Bali Selatan.',
    url: 'https://badungkab.go.id/index.php/kab/berita/74919-gandeng-pt-kai-pemkab-badung-siapkan-moda-trem-penghubung-kuta-hingga-canggu',
  },
  {
    id: 'MED-DEMO-002', title: 'Kemacetan koridor Kuta–Canggu pada jam pulang kerja', publisher: 'Warga Kuta', author: '@wargakuta.demo', type: 'Social Media',
    platform: 'TikTok', topic: 'Kemacetan & Transportasi', sentiment: 'Negative', reach: '184K', engagement: '14.6K', date: '04 Okt 2026',
    location: 'Kuta Utara', language: 'Bahasa Indonesia', excerpt: 'Perjalanan yang biasanya 45 menit dilaporkan mencapai lebih dari dua jam.', video: true,
  },
  {
    id: 'MED-DEMO-003', title: 'Wisatawan membahas kebutuhan transportasi publik menuju Canggu', publisher: 'Bali Travel Forum', author: 'Editorial Community',
    type: 'Social Media', platform: 'Instagram', topic: 'Kemacetan & Transportasi', sentiment: 'Negative', reach: '92K', engagement: '7.8K',
    date: '03 Okt 2026', location: 'Kuta Utara', language: 'English', excerpt: 'Diskusi wisatawan meningkat terkait waktu tempuh bandara menuju Canggu.',
  },
  {
    id: 'MED-DEMO-004', title: 'Sorotan kebersihan setelah akhir pekan di kawasan Pantai Kuta', publisher: 'Komunitas Kuta Bersih', author: 'Admin Komunitas',
    type: 'Citizen / Owned Channel', platform: 'Portal Warga', topic: 'Sampah & Kebersihan', sentiment: 'Negative', reach: '18.3K',
    engagement: '2.1K', date: '04 Okt 2026', location: 'Kuta', language: 'Bahasa Indonesia', excerpt: 'Warga meminta jadwal pengangkutan sampah yang lebih rutin setelah akhir pekan.',
  },
];

type SentimentCounts = { positive:number; neutral:number; negative:number };
type AuthorArticle = { id:string; title:string; media:string; date:string; topic:string; sentiment:string; reach:string; excerpt:string };
type AuthorProfile = { id:string; name:string; role:string; location:string; articles:number; reach:string; engagement:string; media:Array<{name:string;articles:number}>; topics:string[]; sentiment:string; sentimentCounts:SentimentCounts; articlesList:AuthorArticle[] };
type MediaProfile = { id:string; name:string; type:string; articles:number; reach:string; engagement:string; sentiment:string; sentimentCounts:SentimentCounts; authorIds:string[]; topics:string[]; lastPublished:string };

const authors:AuthorProfile[]=[
  {id:'AUT-001',name:'Ayu Lestari',role:'Jurnalis & kontributor independen',location:'Denpasar, Bali',articles:31,reach:'2.4M',engagement:'86K',media:[{name:'Bali Post',articles:18},{name:'Tribun Bali',articles:9},{name:'Mongabay Indonesia',articles:4}],topics:['Pariwisata','Lingkungan','Transportasi'],sentiment:'Neutral',sentimentCounts:{positive:8,neutral:15,negative:8},articlesList:[
    {id:'ART-AYU-01',title:'Tekanan mobilitas di kawasan wisata Bali Selatan',media:'Bali Post',date:'04 Okt 2026',topic:'Kemacetan & Transportasi',sentiment:'Negative',reach:'284K',excerpt:'Lonjakan mobilitas di Kuta dan Canggu memicu kebutuhan penguatan transportasi publik.'},
    {id:'ART-AYU-02',title:'Pelaku wisata menanti solusi angkutan massal',media:'Tribun Bali',date:'01 Okt 2026',topic:'Pariwisata',sentiment:'Neutral',reach:'196K',excerpt:'Pelaku wisata menilai konektivitas antarkawasan menjadi faktor penting bagi pengalaman wisatawan.'},
    {id:'ART-AYU-03',title:'Sampah pesisir meningkat setelah akhir pekan',media:'Mongabay Indonesia',date:'28 Sep 2026',topic:'Sampah & Kebersihan',sentiment:'Negative',reach:'148K',excerpt:'Komunitas pesisir meminta konsistensi pengangkutan dan edukasi pengunjung.'},
  ]},
  {id:'AUT-002',name:'I Made Surya Wijaya',role:'Reporter pemerintahan & kebijakan publik',location:'Badung, Bali',articles:24,reach:'1.8M',engagement:'54K',media:[{name:'Portal Kabupaten Badung',articles:14},{name:'Bali Ekspres',articles:7},{name:'ANTARA Bali',articles:3}],topics:['Kebijakan Publik','Transportasi','Pelayanan'],sentiment:'Positive',sentimentCounts:{positive:13,neutral:9,negative:2},articlesList:[
    {id:'ART-SURYA-01',title:'Pemkab Badung siapkan moda trem Kuta–Canggu',media:'Portal Kabupaten Badung',date:'02 Okt 2026',topic:'Kemacetan & Transportasi',sentiment:'Neutral',reach:'248K',excerpt:'Kolaborasi Pemkab Badung dan PT KAI disiapkan untuk memperkuat konektivitas Bali Selatan.'},
    {id:'ART-SURYA-02',title:'Digitalisasi layanan perizinan dorong kepastian usaha',media:'Bali Ekspres',date:'29 Sep 2026',topic:'Layanan Publik',sentiment:'Positive',reach:'126K',excerpt:'Integrasi layanan perizinan membantu pelaku usaha memantau proses permohonan.'},
    {id:'ART-SURYA-03',title:'Badung memperkuat layanan administrasi kependudukan',media:'ANTARA Bali',date:'22 Sep 2026',topic:'Layanan Publik',sentiment:'Positive',reach:'94K',excerpt:'Peningkatan kapasitas layanan diarahkan untuk mengurangi antrean dan waktu tunggu warga.'},
  ]},
  {id:'AUT-003',name:'Raka Putra',role:'Jurnalis urban & mobilitas',location:'Bali',articles:21,reach:'2.1M',engagement:'97K',media:[{name:'detikBali',articles:12},{name:'Kompas.com',articles:6},{name:'Tribun Bali',articles:3}],topics:['Transportasi','Infrastruktur','Tata Ruang'],sentiment:'Negative',sentimentCounts:{positive:3,neutral:8,negative:10},articlesList:[
    {id:'ART-RAKA-01',title:'Macet Kuta–Canggu kembali menjadi sorotan',media:'detikBali',date:'04 Okt 2026',topic:'Kemacetan & Transportasi',sentiment:'Negative',reach:'412K',excerpt:'Waktu tempuh pada jam sibuk meningkat dan dikeluhkan warga serta wisatawan.'},
    {id:'ART-RAKA-02',title:'Menakar kapasitas jalan di tengah pertumbuhan Canggu',media:'Kompas.com',date:'30 Sep 2026',topic:'Jalan & Infrastruktur',sentiment:'Neutral',reach:'366K',excerpt:'Pertumbuhan aktivitas ekonomi meningkatkan tekanan pada jaringan jalan kawasan.'},
    {id:'ART-RAKA-03',title:'Rekayasa lalu lintas diuji pada koridor wisata',media:'Tribun Bali',date:'26 Sep 2026',topic:'Kemacetan & Transportasi',sentiment:'Neutral',reach:'172K',excerpt:'Pengaturan arus diuji untuk mengurai kepadatan pada beberapa simpang utama.'},
  ]},
  {id:'AUT-004',name:'Ni Luh Diah Prameswari',role:'Jurnalis layanan publik',location:'Badung, Bali',articles:19,reach:'1.3M',engagement:'42K',media:[{name:'Tribun Bali',articles:11},{name:'Bali Post',articles:5},{name:'Kanal Bali',articles:3}],topics:['Layanan Publik','Kesehatan','Kependudukan'],sentiment:'Positive',sentimentCounts:{positive:14,neutral:4,negative:1},articlesList:[
    {id:'ART-DIAH-01',title:'Antrean Dukcapil menurun setelah penambahan loket',media:'Tribun Bali',date:'03 Okt 2026',topic:'Layanan Publik',sentiment:'Positive',reach:'188K',excerpt:'Penambahan loket dan jadwal layanan membantu mengurangi waktu tunggu warga.'},
    {id:'ART-DIAH-02',title:'Warga Mengwi apresiasi layanan administrasi keliling',media:'Bali Post',date:'27 Sep 2026',topic:'Layanan Publik',sentiment:'Positive',reach:'132K',excerpt:'Layanan keliling dinilai membantu warga yang jauh dari pusat layanan.'},
    {id:'ART-DIAH-03',title:'Puskesmas memperluas jadwal layanan akhir pekan',media:'Kanal Bali',date:'20 Sep 2026',topic:'Kesehatan',sentiment:'Positive',reach:'78K',excerpt:'Perluasan jadwal ditujukan untuk meningkatkan akses warga pada layanan dasar.'},
  ]},
  {id:'AUT-005',name:'Kadek Mahendra',role:'Reporter lingkungan & komunitas',location:'Denpasar, Bali',articles:18,reach:'1.1M',engagement:'61K',media:[{name:'NusaBali',articles:13},{name:'ANTARA Bali',articles:4},{name:'Bali Post',articles:1}],topics:['Lingkungan','Sampah','Komunitas'],sentiment:'Neutral',sentimentCounts:{positive:6,neutral:6,negative:6},articlesList:[
    {id:'ART-KADEK-01',title:'Sampah kawasan pantai meningkat pada akhir pekan',media:'NusaBali',date:'04 Okt 2026',topic:'Sampah & Kebersihan',sentiment:'Negative',reach:'206K',excerpt:'Peningkatan kunjungan diikuti kenaikan volume sampah pada sejumlah titik pantai.'},
    {id:'ART-KADEK-02',title:'Komunitas dorong pemilahan sampah dari sumber',media:'ANTARA Bali',date:'25 Sep 2026',topic:'Sampah & Kebersihan',sentiment:'Positive',reach:'114K',excerpt:'Komunitas mendorong pelibatan usaha dan warga untuk memperkuat pemilahan.'},
    {id:'ART-KADEK-03',title:'Jadwal angkut perlu menyesuaikan lonjakan wisatawan',media:'Bali Post',date:'19 Sep 2026',topic:'Sampah & Kebersihan',sentiment:'Neutral',reach:'82K',excerpt:'Penyesuaian jadwal diusulkan untuk kawasan dengan lonjakan volume musiman.'},
  ]},
];

const mediaProfiles:MediaProfile[]=[
  {id:'MED-PUB-001',name:'Portal Kabupaten Badung',type:'Owned Media',articles:186,reach:'2.8M',engagement:'84K',sentiment:'Positive',sentimentCounts:{positive:102,neutral:68,negative:16},authorIds:['AUT-002'],topics:['Kebijakan Publik','Pelayanan','Transportasi'],lastPublished:'04 Okt 2026 · 16:10'},
  {id:'MED-PUB-002',name:'Bali Post',type:'Media Online & Print',articles:128,reach:'3.4M',engagement:'118K',sentiment:'Neutral',sentimentCounts:{positive:44,neutral:60,negative:24},authorIds:['AUT-001','AUT-004','AUT-005'],topics:['Pariwisata','Lingkungan','Layanan Publik'],lastPublished:'04 Okt 2026 · 14:45'},
  {id:'MED-PUB-003',name:'Tribun Bali',type:'Media Online',articles:116,reach:'3.1M',engagement:'142K',sentiment:'Negative',sentimentCounts:{positive:28,neutral:37,negative:51},authorIds:['AUT-001','AUT-003','AUT-004'],topics:['Transportasi','Pariwisata','Layanan Publik'],lastPublished:'04 Okt 2026 · 15:20'},
  {id:'MED-PUB-004',name:'detikBali',type:'Media Online',articles:104,reach:'4.2M',engagement:'186K',sentiment:'Negative',sentimentCounts:{positive:20,neutral:34,negative:50},authorIds:['AUT-003'],topics:['Transportasi','Infrastruktur','Pariwisata'],lastPublished:'04 Okt 2026 · 17:05'},
  {id:'MED-PUB-005',name:'NusaBali',type:'Media Online & Print',articles:92,reach:'2.2M',engagement:'96K',sentiment:'Neutral',sentimentCounts:{positive:31,neutral:39,negative:22},authorIds:['AUT-005'],topics:['Lingkungan','Komunitas','Pemerintahan'],lastPublished:'04 Okt 2026 · 13:30'},
  {id:'MED-PUB-006',name:'ANTARA Bali',type:'News Agency',articles:84,reach:'2.9M',engagement:'74K',sentiment:'Positive',sentimentCounts:{positive:42,neutral:31,negative:11},authorIds:['AUT-002','AUT-005'],topics:['Pemerintahan','Ekonomi','Lingkungan'],lastPublished:'04 Okt 2026 · 12:15'},
  {id:'MED-PUB-009',name:'Kompas.com',type:'Media Online',articles:76,reach:'5.1M',engagement:'172K',sentiment:'Neutral',sentimentCounts:{positive:23,neutral:33,negative:20},authorIds:['AUT-003'],topics:['Transportasi','Tata Ruang','Infrastruktur'],lastPublished:'04 Okt 2026 · 11:35'},
  {id:'MED-PUB-008',name:'Bali Ekspres',type:'Media Online & Print',articles:62,reach:'1.5M',engagement:'46K',sentiment:'Neutral',sentimentCounts:{positive:22,neutral:29,negative:11},authorIds:['AUT-002'],topics:['Pemerintahan','Pelayanan','Ekonomi'],lastPublished:'03 Okt 2026 · 16:20'},
  {id:'MED-PUB-007',name:'Mongabay Indonesia',type:'Media Online',articles:48,reach:'1.7M',engagement:'63K',sentiment:'Negative',sentimentCounts:{positive:8,neutral:18,negative:22},authorIds:['AUT-001'],topics:['Lingkungan','Pesisir','Sampah'],lastPublished:'03 Okt 2026 · 10:40'},
  {id:'MED-PUB-010',name:'Kanal Bali',type:'Media Online',articles:44,reach:'980K',engagement:'38K',sentiment:'Positive',sentimentCounts:{positive:25,neutral:14,negative:5},authorIds:['AUT-004'],topics:['Kesehatan','Pelayanan','Kependudukan'],lastPublished:'02 Okt 2026 · 09:10'},
];

const tabs: Tab[] = ['Ringkasan', 'Berita & Postingan', 'Media & Akun', 'Pencarian', 'Analitik', 'Peta & Relasi', 'Tren'];

export function MediaMonitoring({navigate}:{navigate:(target:'Topics'|'Findings')=>void}) {
  const [tab,setTab]=useState<Tab>('Ringkasan');
  const [selected,setSelected]=useState<ContentRecord|null>(null);
  const [query,setQuery]=useState('canggu macet');
  return <section className={styles.root}>
    <div className={styles.hero}><div><span>MEDIA INTELLIGENCE</span><h2>Media Monitoring</h2><p>Pantau isi percakapan, pihak yang mengamplifikasi, jangkauan, dan perubahan narasi dalam satu workspace.</p></div><div><small>MONITORED PUBLIC WEB</small><b>04 Agu–04 Okt 2026</b><em>Dataset demo terkurasi</em></div></div>
    <nav className={styles.tabs} aria-label="Media Monitoring tabs">{tabs.map(item=><button key={item} className={tab===item?styles.active:''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='Ringkasan'&&<Summary open={setSelected} navigate={navigate}/>}
    {tab==='Berita & Postingan'&&<ContentExplorer open={setSelected}/>}
    {tab==='Media & Akun'&&<Publishers/>}
    {tab==='Pencarian'&&<Search query={query} setQuery={setQuery} open={setSelected}/>}
    {tab==='Analitik'&&<Analytics/>}
    {tab==='Peta & Relasi'&&<Relationships navigate={navigate}/>}
    {tab==='Tren'&&<Trends navigate={navigate}/>}
    {selected&&<ContentDetail record={selected} close={()=>setSelected(null)} navigate={navigate}/>}
  </section>;
}

function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className={styles.metric}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}

function Summary({open,navigate}:{open:(record:ContentRecord)=>void;navigate:(target:'Topics'|'Findings')=>void}){
  return <><div className={styles.metrics}><Metric label="Konten Terpantau" value="42,680" note="+10.4% dari periode sebelumnya"/><Metric label="Media Konvensional" value="8,964" note="21% dari konten terpantau"/><Metric label="Social Media" value="29,876" note="70% dari konten terpantau"/><Metric label="Potensi Jangkauan" value="12.8M" note="Demo terkontrol"/><Metric label="Engagement" value="846K" note="Demo terkontrol"/></div>
    <div className={styles.summaryGrid}><section className={styles.panel}><div className={styles.title}><div><h3>Volume Media</h3><p>Media konvensional dan social media</p></div><span className={styles.legend}>● Social &nbsp; ● Conventional</span></div><div className={styles.volumeChart}>{[36,43,39,57,48,66,62,78,71,88,83,96].map((value,index)=><div key={index}><i style={{height:`${value}%`}}/><em style={{height:`${Math.max(18,value*.38)}%`}}/></div>)}</div><div className={styles.chartLabels}><span>04 Agu</span><span>19 Agu</span><span>03 Sep</span><span>18 Sep</span><span>04 Okt</span></div></section>
      <section className={styles.panel}><div className={styles.title}><div><h3>Top Issues</h3><p>Volume dan perubahan perhatian</p></div><button onClick={()=>navigate('Topics')}>Buka Isu Daerah →</button></div><div className={styles.ranking}>{[['Kemacetan & Transportasi','9,840','+24.6%'],['Sampah & Kebersihan','7,215','+18.2%'],['Jalan & Infrastruktur','6,482','+9.1%'],['Pariwisata','5,940','+12.4%']].map((item,index)=><div key={item[0]}><span>{index+1}</span><p><b>{item[0]}</b><small>{item[1]} percakapan</small></p><em>{item[2]}</em></div>)}</div></section></div>
    <div className={styles.three}><section className={styles.panel}><div className={styles.title}><div><h3>Emerging Narratives</h3><p>Pertumbuhan baru dan tidak biasa</p></div></div>{[['Transportasi massal Bali Selatan','Pertama 28 Sep','+186%'],['Jam puncak Kuta–Canggu','Pertama 01 Okt','+94%'],['Sampah pasca akhir pekan','Pertama 03 Okt','+71%']].map(item=><div className={styles.signal} key={item[0]}><i>↗</i><p><b>{item[0]}</b><small>{item[1]}</small></p><strong>{item[2]}</strong></div>)}</section>
      <section className={styles.panel}><div className={styles.title}><div><h3>Media Attention</h3><p>Isu dengan kenaikan liputan tajam</p></div></div>{[['Kemacetan & Transportasi',86],['Sampah & Kebersihan',64],['Pariwisata',49],['Infrastruktur',37]].map(item=><div className={styles.attention} key={item[0]}><p><span>{item[0]}</span><b>{item[1]}%</b></p><i><em style={{width:`${item[1]}%`}}/></i></div>)}</section>
      <section className={styles.panel}><div className={styles.title}><div><h3>Sentiment</h3><p>Semua konten terpantau</p></div></div><div className={styles.sentiment}><div><strong>58.7%</strong><span>Positif</span></div><p><span><i className={styles.positive}/>Positive <b>58.7%</b></span><span><i className={styles.neutral}/>Neutral <b>27.9%</b></span><span><i className={styles.negative}/>Negative <b>13.4%</b></span></p></div></section></div>
    <section className={styles.panel}><div className={styles.title}><div><h3>Konten Terbaru</h3><p>Media, postingan, dan owned channel dalam konteks yang sama</p></div><button onClick={()=>navigate('Findings')}>Lihat Findings →</button></div><ContentTable data={records} open={open}/></section></>;
}

function FilterBar(){return <div className={styles.filters}><label>Periode<select><option>04 Agu–04 Okt 2026</option></select></label><label>Media Type<select><option>Semua tipe</option><option>Social Media</option><option>Media Konvensional</option></select></label><label>Platform<select><option>Semua platform</option><option>TikTok</option><option>Media Online</option></select></label><label>Topic<select><option>Semua topik</option><option>Kemacetan & Transportasi</option></select></label><label>Sentiment<select><option>Semua sentimen</option><option>Negative</option></select></label><button>＋ Filter</button></div>}

function ContentExplorer({open}:{open:(record:ContentRecord)=>void}){return <><FilterBar/><section className={styles.panel}><div className={styles.title}><div><h3>Berita & Postingan</h3><p>Konten mentah lintas media dengan klasifikasi dan evidence</p></div><span className={styles.demo}>4 record contoh · 1 sumber resmi</span></div><ContentTable data={records} open={open}/></section></>}

function ContentTable({data,open}:{data:ContentRecord[];open:(record:ContentRecord)=>void}){return <div className={styles.tableWrap}><div className={`${styles.tableRow} ${styles.tableHead}`}><b>CONTENT</b><b>MEDIA / ACCOUNT</b><b>TYPE</b><b>TOPIC</b><b>SENTIMENT</b><b>REACH</b><b>ENGAGEMENT</b><b>DATE</b></div>{data.map(record=><button className={styles.tableRow} key={record.id} onClick={()=>open(record)}><span><strong>{record.title}</strong><small>{record.id} · {record.platform}</small></span><span className={styles.publisherCell}><b>{record.publisher}</b>{record.author&&<small>{record.author}</small>}</span><span>{record.type}</span><span>{record.topic}</span><span className={record.sentiment==='Negative'?styles.bad:record.sentiment==='Positive'?styles.good:styles.mid}>{record.sentiment}</span><span>{record.reach}</span><span>{record.engagement}</span><span>{record.date}</span></button>)}</div>}

function Publishers(){
  const [view,setView]=useState<'media'|'authors'>('media');
  const [profile,setProfile]=useState<{kind:'media'|'author';id:string}|null>(null);
  const [articleDetail,setArticleDetail]=useState<{article:AuthorArticle;author:AuthorProfile}|null>(null);
  const selectedMedia=profile?.kind==='media'?mediaProfiles.find(item=>item.id===profile.id):undefined;
  const selectedAuthor=profile?.kind==='author'?authors.find(item=>item.id===profile.id):undefined;
  function openAuthor(id:string){setProfile({kind:'author',id});}
  function openMediaByName(name:string){const media=mediaProfiles.find(item=>item.name===name);if(media)setProfile({kind:'media',id:media.id});}
  return <><section className={styles.contributorIntro}><div><span>CONTRIBUTOR INTELLIGENCE</span><h3>Siapa yang paling banyak membentuk pemberitaan?</h3><p>Media dan penulis dianalisis sebagai entitas terpisah. Satu penulis dapat berkontribusi ke beberapa media.</p></div><div><article><small>MEDIA TERPANTAU</small><b>186</b></article><article><small>PENULIS TERIDENTIFIKASI</small><b>342</b></article><article><small>MULTI-MEDIA CONTRIBUTORS</small><b>47</b></article></div></section>
    <nav className={styles.contributorTabs} aria-label="Media dan kontributor"><button className={view==='media'?styles.selectedContributorTab:''} onClick={()=>setView('media')}><span>▤</span><div><b>Top Media</b><small>Ranking berdasarkan jumlah konten</small></div></button><button className={view==='authors'?styles.selectedContributorTab:''} onClick={()=>setView('authors')}><span>♙</span><div><b>Top Penulis / Kontributor</b><small>Lintas media dan topik</small></div></button></nav>
    <FilterBar/>
    {view==='media'?<section className={styles.contributorPanel}><div className={styles.contributorHeader}><div><h3>Top Media</h3><p>Perbandingan volume artikel dan distribusi sentimen. Klik baris untuk melihat penulis serta detail artikelnya.</p></div><span>{mediaProfiles.length} contoh media</span></div><div className={styles.contributorList}><div className={`${styles.contributorListHead} ${styles.mediaListRow}`}><span>#</span><span>MEDIA</span><span>ARTIKEL</span><span>POSITIVE</span><span>NEUTRAL</span><span>NEGATIVE</span><span>AVG. SENTIMENT</span><span>REACH</span><span/></div>{mediaProfiles.map((media,index)=><button className={styles.mediaListRow} key={media.id} onClick={()=>setProfile({kind:'media',id:media.id})}><span className={styles.rankNumber}>{String(index+1).padStart(2,'0')}</span><span className={styles.entityCell}><i>{media.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</i><span><b>{media.name}</b><small>{media.type} · {media.authorIds.length} penulis</small></span></span><strong>{media.articles}</strong><span className={styles.positiveCount}>{media.sentimentCounts.positive}</span><span className={styles.neutralCount}>{media.sentimentCounts.neutral}</span><span className={styles.negativeCount}>{media.sentimentCounts.negative}</span><em className={media.sentiment==='Negative'?styles.bad:media.sentiment==='Positive'?styles.good:styles.mid}>{media.sentiment}</em><span>{media.reach}</span><i>→</i></button>)}</div></section>
      :<section className={styles.contributorPanel}><div className={styles.contributorHeader}><div><h3>Top Penulis / Kontributor</h3><p>Perbandingan kontribusi individu lintas media beserta sentimen rata-rata seluruh artikelnya.</p></div><span>{authors.length} profil contoh</span></div><div className={styles.contributorList}><div className={`${styles.contributorListHead} ${styles.authorListRow}`}><span>#</span><span>PENULIS / MEDIA</span><span>ARTIKEL</span><span>POSITIVE</span><span>NEUTRAL</span><span>NEGATIVE</span><span>AVG. SENTIMENT</span><span>MEDIA</span><span/></div>{authors.map((author,index)=><button className={styles.authorListRow} key={author.id} onClick={()=>openAuthor(author.id)}><span className={styles.rankNumber}>{String(index+1).padStart(2,'0')}</span><span className={styles.entityCell}><i>{author.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</i><span><b>{author.name}</b><small>{author.media.map(media=>media.name).join(' · ')}</small></span></span><strong>{author.articles}</strong><span className={styles.positiveCount}>{author.sentimentCounts.positive}</span><span className={styles.neutralCount}>{author.sentimentCounts.neutral}</span><span className={styles.negativeCount}>{author.sentimentCounts.negative}</span><em className={author.sentiment==='Negative'?styles.bad:author.sentiment==='Positive'?styles.good:styles.mid}>{author.sentiment}</em><span>{author.media.length}</span><i>→</i></button>)}</div></section>}
    {profile&&<div className={styles.overlay} role="dialog" aria-modal="true" aria-labelledby="contributor-profile-title"><article className={styles.contributorDetail}>
      <header><div><small>{profile.kind==='media'?'MEDIA PROFILE':'CONTRIBUTOR PROFILE'}</small><h2 id="contributor-profile-title">{selectedMedia?.name||selectedAuthor?.name}</h2><p>{selectedMedia?.type||selectedAuthor?.role}</p></div><button onClick={()=>setProfile(null)} aria-label="Tutup">×</button></header>
      {selectedMedia&&<MediaProfileDetail media={selectedMedia} openAuthor={openAuthor} openArticle={(article,author)=>setArticleDetail({article,author})}/>}
      {selectedAuthor&&<AuthorProfileDetail author={selectedAuthor} openMedia={openMediaByName} openArticle={article=>setArticleDetail({article,author:selectedAuthor})}/>}
    </article></div>}
    {articleDetail&&<ContributorArticleDetail article={articleDetail.article} author={articleDetail.author} close={()=>setArticleDetail(null)}/>}
  </>;
}

function MediaProfileDetail({media,openAuthor,openArticle}:{media:MediaProfile;openAuthor:(id:string)=>void;openArticle:(article:AuthorArticle,author:AuthorProfile)=>void}){
  const contributors=media.authorIds.map(id=>authors.find(item=>item.id===id)).filter((item):item is AuthorProfile=>Boolean(item));
  const articles=contributors.flatMap(author=>author.articlesList.filter(article=>article.media===media.name).map(article=>({...article,author:author.name,authorId:author.id})));
  return <div className={styles.profileBody}><section className={styles.profileMetrics}><article><small>ARTIKEL</small><b>{media.articles}</b></article><article><small>POSITIVE</small><b className={styles.positiveCount}>{media.sentimentCounts.positive}</b></article><article><small>NEUTRAL</small><b className={styles.neutralCount}>{media.sentimentCounts.neutral}</b></article><article><small>NEGATIVE</small><b className={styles.negativeCount}>{media.sentimentCounts.negative}</b></article><article><small>AVG. SENTIMENT</small><b>{media.sentiment}</b></article></section><div className={styles.profileColumns}><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Penulis Teratas di {media.name}</h3><p>Klik penulis untuk melihat kontribusinya di media lain.</p></div></div><div className={styles.mediaAuthors}>{contributors.map((author,index)=><button key={author.id} onClick={()=>openAuthor(author.id)}><span>{index+1}</span><div><b>{author.name}</b><small>{author.role}</small><p>{author.topics.join(' · ')}</p></div><strong>{author.media.find(item=>item.name===media.name)?.articles||0}<small>artikel di media ini</small></strong><i>→</i></button>)}</div></section><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Topik Dominan</h3><p>Fokus pemberitaan media</p></div></div><div className={styles.topicCloud}>{media.topics.map((topic,index)=><span key={topic}>{topic}<b>{[38,27,19][index]}%</b></span>)}</div><div className={styles.profileNote}><b>Aktivitas media</b><p>{media.reach} potential reach · {media.engagement} engagement. Terakhir terbit {media.lastPublished}.</p></div></section></div><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Contoh Penulisan Terbaru</h3><p>Klik artikel untuk melihat source detail dan analisis AI.</p></div></div>{articles.length?<div className={styles.articleHistory}>{articles.map(article=><button key={article.id} onClick={()=>{const author=authors.find(item=>item.id===article.authorId);if(author)openArticle(article,author);}}><div><b>{article.title}</b><small>{article.author} · {article.date}</small></div><span>{article.topic}</span><em className={article.sentiment==='Negative'?styles.bad:article.sentiment==='Positive'?styles.good:styles.mid}>{article.sentiment}</em><strong>{article.reach}</strong></button>)}</div>:<div className={styles.emptyProfile}>Belum ada contoh artikel ber-byline pada dataset demo ini.</div>}</section></div>;
}

function AuthorProfileDetail({author,openMedia,openArticle}:{author:AuthorProfile;openMedia:(name:string)=>void;openArticle:(article:AuthorArticle)=>void}){
  return <div className={styles.profileBody}><div className={styles.authorHero}><span>{author.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</span><div><small>{author.id} · {author.location}</small><h3>{author.name}</h3><p>{author.role}</p><div>{author.topics.map(topic=><em key={topic}>{topic}</em>)}</div></div><i>MULTI-MEDIA CONTRIBUTOR</i></div><section className={styles.profileMetrics}><article><small>TOTAL ARTIKEL</small><b>{author.articles}</b></article><article><small>POSITIVE</small><b className={styles.positiveCount}>{author.sentimentCounts.positive}</b></article><article><small>NEUTRAL</small><b className={styles.neutralCount}>{author.sentimentCounts.neutral}</b></article><article><small>NEGATIVE</small><b className={styles.negativeCount}>{author.sentimentCounts.negative}</b></article><article><small>AVG. SENTIMENT</small><b>{author.sentiment}</b></article></section><div className={styles.profileColumns}><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Kontribusi per Media</h3><p>Penulis tidak dikunci pada satu organisasi media.</p></div></div><div className={styles.authorMediaBreakdown}>{author.media.map(media=><button key={media.name} onClick={()=>openMedia(media.name)}><span>{media.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</span><div><b>{media.name}</b><i><em style={{width:`${Math.min(100,media.articles/author.articles*100*2)}%`}}/></i></div><strong>{media.articles}<small>artikel</small></strong><em>Profil media →</em></button>)}</div></section><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Contributor Insight</h3><p>{author.reach} reach · {author.engagement} engagement</p></div></div><div className={styles.insightList}><p><span>01</span><b>{author.media.length} media berbeda</b><small>Kontributor tidak terikat pada satu media.</small></p><p><span>02</span><b>{author.topics[0]} menjadi topik utama</b><small>Diukur dari distribusi artikel dan reach.</small></p><p><span>03</span><b>{author.sentiment} average sentiment</b><small>Rata-rata klasifikasi sentimen seluruh artikel.</small></p></div></section></div><section className={styles.profilePanel}><div className={styles.profileTitle}><div><h3>Riwayat Penulisan</h3><p>Klik artikel untuk membuka detail lengkap.</p></div><b>{author.articlesList.length} contoh artikel</b></div><div className={styles.articleHistory}>{author.articlesList.map(article=><button key={article.id} onClick={()=>openArticle(article)}><div><b>{article.title}</b><small>{article.media} · {article.date}</small></div><span>{article.topic}</span><em className={article.sentiment==='Negative'?styles.bad:article.sentiment==='Positive'?styles.good:styles.mid}>{article.sentiment}</em><strong>{article.reach}</strong></button>)}</div></section></div>;
}

function ContributorArticleDetail({article,author,close}:{article:AuthorArticle;author:AuthorProfile;close:()=>void}){
  return <div className={`${styles.overlay} ${styles.articleOverlay}`} role="dialog" aria-modal="true" aria-labelledby="contributor-article-title"><article className={styles.articleDetailModal}><header><div><small>{article.id} · ARTICLE DETAIL</small><h2 id="contributor-article-title">{article.title}</h2><p>{article.media} · {author.name} · {article.date}</p></div><button onClick={close} aria-label="Tutup detail artikel">×</button></header><div className={styles.articleDetailBody}><section><div className={styles.articleSourceCard}><span>MEDIA ARTICLE</span><b>{article.media}</b><h3>{article.title}</h3><p>{article.excerpt}</p></div><h3>Source Detail</h3><dl><div><dt>Media</dt><dd>{article.media}</dd></div><div><dt>Penulis / Byline</dt><dd>{author.name}</dd></div><div><dt>Published</dt><dd>{article.date}</dd></div><div><dt>Article ID</dt><dd>{article.id}</dd></div></dl><p className={styles.disclaimer}>Controlled demo record. URL sumber dapat disambungkan saat connector media aktif.</p></section><section><h3>AI Article Analysis</h3><div className={styles.articleAnalysisGrid}><article><small>TOPIC</small><b>{article.topic}</b></article><article><small>SENTIMENT</small><b className={article.sentiment==='Negative'?styles.bad:article.sentiment==='Positive'?styles.good:styles.mid}>{article.sentiment}</b></article><article><small>POTENTIAL REACH</small><b>{article.reach}</b></article><article><small>AUTHOR AVG. SENTIMENT</small><b>{author.sentiment}</b></article></div><h3>AI Summary</h3><blockquote>{article.excerpt} Artikel ini menjadi salah satu sinyal dalam pola pemberitaan {article.topic.toLowerCase()} dan diperhitungkan dalam profil sentimen {author.name}.</blockquote><h3>Contributor Context</h3><dl><div><dt>Total artikel penulis</dt><dd>{author.articles}</dd></div><div><dt>Media teridentifikasi</dt><dd>{author.media.length}</dd></div><div><dt>Positive / Neutral / Negative</dt><dd>{author.sentimentCounts.positive} / {author.sentimentCounts.neutral} / {author.sentimentCounts.negative}</dd></div></dl></section></div></article></div>;
}

function Search({query,setQuery,open}:{query:string;setQuery:(value:string)=>void;open:(record:ContentRecord)=>void}){const found=useMemo(()=>records.filter(record=>`${record.title} ${record.excerpt} ${record.topic}`.toLowerCase().includes(query.toLowerCase().split(' ')[0]||'')),[query]);return <><section className={styles.searchPanel}><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Cari intelligence media"/><button>Cari Intelligence</button></section><FilterBar/><div className={styles.searchMeta}><p><b>{found.length} contoh hasil</b> untuk “{query}”</p><div><button>☆ Save Search</button><button>＋ Create Monitoring Rule</button></div></div><section className={styles.panel}><ContentTable data={found} open={open}/></section></>}

function Analytics(){return <><div className={styles.analyticsNav}>{['Conversation','Sentiment & Emotion','Engagement','Topic','Geography','Comparison'].map((x,i)=><button className={i===0?styles.selected:''} key={x}>{x}</button>)}</div><div className={styles.metrics}><Metric label="Mention Volume" value="42,680" note="+10.4%"/><Metric label="Share of Voice" value="38.6%" note="Top issue: transportasi"/><Metric label="Negative Sentiment" value="13.4%" note="+2.8 poin"/><Metric label="Engagement Rate" value="6.6%" note="Demo terkontrol"/><Metric label="Source Diversity" value="7" note="Kelompok sumber"/></div><div className={styles.summaryGrid}><section className={styles.panel}><div className={styles.title}><div><h3>Topic × Sentiment</h3><p>Distribusi sentimen pada isu utama</p></div></div>{[['Kemacetan',18,31,51],['Sampah',34,29,37],['Infrastruktur',48,36,16],['Pariwisata',69,24,7]].map(item=><div className={styles.stacked} key={item[0]}><span>{item[0]}</span><i><em style={{width:`${item[1]}%`}}/><b style={{width:`${item[2]}%`}}/><strong style={{width:`${item[3]}%`}}/></i></div>)}</section><section className={styles.panel}><div className={styles.title}><div><h3>Source Mix</h3><p>Porsi sumber percakapan</p></div></div><div className={styles.sourceMix}>{[['Social Media','70%'],['Media Konvensional','21%'],['Citizen / Owned','9%']].map(item=><p key={item[0]}><span>{item[0]}</span><b>{item[1]}</b></p>)}</div></section></div></>}

function Relationships({navigate}:{navigate:(target:'Topics'|'Findings')=>void}){return <div className={styles.relationshipGrid}><section className={styles.panel}><div className={styles.title}><div><h3>Network</h3><p>Pihak yang mengamplifikasi isu transportasi</p></div></div><div className={styles.network}><span className={styles.nodeMain}>Kemacetan<br/>Kuta–Canggu</span><span className={styles.nodeA}>Media lokal</span><span className={styles.nodeB}>Travel creators</span><span className={styles.nodeC}>Warga Kuta</span><span className={styles.nodeD}>Wisatawan</span></div></section><section className={styles.panel}><div className={styles.title}><div><h3>Entity & Narrative Relationship</h3><p>Relasi lokasi, aktor, organisasi, dan narasi</p></div></div><div className={styles.links}>{[['Kuta Utara','Kemacetan','Jam puncak'],['Wisatawan','Transportasi publik','Pengalaman destinasi'],['Pemkab Badung','Moda trem','Mobilitas Bali Selatan'],['Media lokal','Canggu','Overdevelopment']].map(item=><p key={item[0]}><b>{item[0]}</b><i>→</i><span>{item[1]}</span><i>→</i><em>{item[2]}</em></p>)}</div><div className={styles.actions}><button onClick={()=>navigate('Topics')}>View Related Issue</button><button onClick={()=>navigate('Findings')}>View Findings</button></div></section></div>}

function Trends({navigate}:{navigate:(target:'Topics'|'Findings')=>void}){return <><div className={styles.trendGrid}>{[['Rising Topics','Kemacetan & Transportasi','+24.6%'],['Rising Keywords','trem · macet · canggu','+186%'],['Rising Actors','Dishub · PT KAI','+78%'],['Rising Locations','Kuta Utara','+42%'],['Media Attention','Transportasi publik','+64%']].map((item,index)=><article key={item[0]}><small>{item[0]}</small><strong>{item[1]}</strong><span>↗ {item[2]}</span><i style={{width:`${82-index*8}%`}}/></article>)}</div><section className={styles.panel}><div className={styles.title}><div><h3>Emerging Narratives</h3><p>First detected, growth, source count, dan potential reach</p></div><button onClick={()=>navigate('Findings')}>Create / View Finding →</button></div><div className={styles.narratives}>{[['Transportasi massal menjadi kebutuhan mendesak Bali Selatan','28 Sep 2026','+186%','18 sources','1.8M'],['Kemacetan jam puncak memengaruhi pengalaman wisatawan','01 Okt 2026','+94%','12 sources','940K'],['Pertumbuhan Canggu dikaitkan dengan tekanan infrastruktur','02 Okt 2026','+81%','9 sources','610K']].map(item=><div key={item[0]}><strong>{item[0]}</strong><span>First detected {item[1]}</span><b>{item[2]}</b><em>{item[3]}</em><i>{item[4]} reach</i></div>)}</div></section></>}

function ContentDetail({record,close,navigate}:{record:ContentRecord;close:()=>void;navigate:(target:'Topics'|'Findings')=>void}){return <div className={styles.overlay} role="dialog" aria-modal="true" aria-labelledby="media-detail-title"><article className={styles.detail}><header><div><small>{record.id} · {record.type}</small><h2 id="media-detail-title">{record.title}</h2></div><button onClick={close}>×</button></header><div className={styles.detailGrid}><section>{record.video?<><Image src="/demo-kuta-traffic.svg" width={800} height={450} alt="Frame video demo kemacetan Kuta"/><span className={styles.videoTag}>VIDEO DEMO · 02:14–02:37</span></>:<div className={styles.articlePreview}><span>MEDIA EVIDENCE</span><b>{record.publisher}</b><p>{record.excerpt}</p></div>}<h3>Source & Evidence</h3><dl><div><dt>Publisher</dt><dd>{record.publisher}</dd></div><div><dt>Penulis / Byline</dt><dd>{record.author||'Tidak teridentifikasi'}</dd></div><div><dt>Published</dt><dd>{record.date}</dd></div><div><dt>Location</dt><dd>{record.location}</dd></div><div><dt>Language</dt><dd>{record.language}</dd></div></dl>{record.url?<a href={record.url} target="_blank" rel="noreferrer">Buka sumber asli ↗</a>:<p className={styles.disclaimer}>Controlled demo record. Tidak diklaim sebagai sumber publik asli.</p>}</section><section><h3>Transcript / Content</h3><blockquote>{record.excerpt}</blockquote><h3>AI Analysis</h3><dl><div><dt>Topic</dt><dd>{record.topic}</dd></div><div><dt>Sentiment</dt><dd>{record.sentiment}</dd></div><div><dt>Reach</dt><dd>{record.reach}</dd></div><div><dt>Engagement</dt><dd>{record.engagement}</dd></div></dl><h3>Related Intelligence</h3><p>Konten ini mendukung cluster isu transportasi dan dapat ditambahkan sebagai evidence untuk Finding terpisah.</p><div className={styles.actions}><button onClick={()=>{close();navigate('Topics')}}>View Related Issue</button><button onClick={()=>{close();navigate('Findings')}}>Add as Evidence / Create Finding</button></div></section></div></article></div>}
